package:
  name: numpy
  version: 1.26.0rc1
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/33/a9/1233954ed69e96e829e6615a6e4a68e8c99d599661edff756fb4300c9a0b/numpy-1.26.0rc1.tar.gz
  sha256: 49a8cafece27db51fd9ec78c044546b15b0c9bf95466c57ada9eeae64075c2f8

  patches:
    - patches/0001-BLD-lower-minimum-GCC-version-to-8.3.patch

build:
  script: |
    export CFLAGS=${SIDE_MODULE_CFLAGS}
    export LDFLAGS=${SIDE_MODULE_LDFLAGS}
  backend-flags: |
    setup-args=--cross-file=$PYODIDE_ROOT/tools/emscripten.meson.cross
    -Ddisable-optimization=true
    -Dallow-noblas=true
  cflags: |
    -Wno-return-type

requirements:
  host:
    # FIXME: openblas.pc and cblas.h aren't installed under packages/.libs/
    - openblas
  run:
    - packaging

about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD
